name: Перезапуск Telegram-бота
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Подключение к серверу и перезапуск бота
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /***/testbot || exit 1
            
            echo "=== Обновление кода ==="
            git reset --hard
            git pull origin main
            
            echo "=== Остановка старого процесса ==="
            pkill -f testbot.py || true
            sleep 3
            
            echo "=== Проверка что процесс завершился ==="
            if pgrep -f testbot.py; then
                echo "Принудительно завершаем процесс..."
                pkill -9 -f testbot.py || true
                sleep 2
            fi
            
            echo "=== Запуск нового процесса ==="
            # Очищаем лог файл
            > /***/testbot/log.txt
            
            # Запускаем с максимальной изоляцией от SSH сессии
            setsid nohup /***/testbot/venv/bin/python /***/testbot/testbot.py > /***/testbot/log.txt 2>&1 < /dev/null &
            
            # Сохраняем PID
            echo $! > /***/testbot/bot.pid
            
            echo "=== Ожидание запуска ==="
            sleep 5
            
            echo "=== Проверка процесса ==="
            if pgrep -f testbot.py; then
                echo "✅ Бот успешно запущен!"
                ps aux | grep testbot.py | grep -v grep
            else
                echo "❌ Бот не запустился!"
            fi
            
            echo "=== Проверка лога ==="
            if [ -s /***/testbot/log.txt ]; then
                echo "Последние строки лога:"
                tail -n 20 /***/testbot/log.txt
            else
                echo "Лог файл пуст или не создан"
            fi
            
            echo "=== Информация о Python окружении ==="
            echo "Python путь: /***/testbot/venv/bin/python"
            /***/testbot/venv/bin/python --version
            echo "Рабочая директория: $(pwd)"
