name: Перезапуск Telegram-бота

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Подключение к серверу и перезапуск бота
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/testbot
            git pull origin main
            echo "Running processes:"
            ps aux | grep testbot.py
            pkill -f testbot.py || true
            nohup python3 /root/testbot/testbot.py > /root/testbot/log.txt 2>&1 &
