name: Перезапуск Telegram-бота

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Подключение к серверу и перезапуск бота
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/testbot/testbot
            git pull origin main
            echo "Stopping existing bot..."
            pkill -f testbot.py || true
            sleep 2
            while pgrep -f testbot.py; do
              echo "Waiting for bot to shut down..."
              sleep 1
            done
            echo "Starting bot..."
            cd /root/testbot/testbot
            nohup python3 testbot.py &
          
