name: Перезапуск Telegram-бота

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Подключение к серверу и перезапуск бота
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/testbot  # Укажи путь до каталога с ботом
            git pull origin main

            # Установка зависимостей (если есть requirements.txt)
            if [ -f requirements.txt ]; then
              pip3 install -r requirements.txt
            fi

            # Перезапуск бота
            pkill -f testbot.py || true
            nohup python3 testbot.py > log.txt 2>&1 &
