name: Перезапуск Telegram-бота

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Подключение к серверу и перезапуск бота
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /***/testbot || exit 1
            
            git reset --hard
            git pull origin main
            pkill -f testbot.py || true
          
            echo "Запускаем бот через python из venv..."
            nohup /***/testbot/venv/bin/python /***/testbot/testbot.py > /***/testbot/log.txt 2>&1 &
            
            echo "Проверка запущенных процессов:"
            ps aux | grep testbot.py
            
            echo "Вывод последних строк лога:"
            tail -n 30 /***/testbot/log.txt

